services:
    init-kafka:
      image: confluentinc/cp-kafka:latest
      depends_on:
        - kafka
      entrypoint: [ '/bin/sh', '-c' ]
      command: |
        "
        kafka-topics --bootstrap-server b-1.kafkaclustorlogingest.l22s80.c2.kafka.ap-south-1.amazonaws.com:9096 --list

        echo -e 'Creating kafka topics'
        kafka-topics --bootstrap-server b-1.kafkaclustorlogingest.l22s80.c2.kafka.ap-south-1.amazonaws.com:9096 --create --if-not-exists --topic logs-topic --replication-factor 3 --partitions 8

        kafka-topics --bootstrap-server b-1.kafkaclustorlogingest.l22s80.c2.kafka.ap-south-1.amazonaws.com:9096 --list
        "
      networks:
        - kafka-net

    app:
        build: .
        ports:
          - "3500:3500"
        environment:
          KAFKA_BROKERS: "b-1.kafkaclustorlogingest.l22s80.c2.kafka.ap-south-1.amazonaws.com:9096,b-2.kafkaclustorlogingest.l22s80.c2.kafka.ap-south-1.amazonaws.com:9096,b-3.kafkaclustorlogingest.l22s80.c2.kafka.ap-south-1.amazonaws.com:9096"
        depends_on:
          - init-kafka
        networks:
          - kafka-net

networks:
    kafka-net:
      driver: bridge
