version: 2.1

jobs:
    install_dependencies:
        docker:
        - image: cimg/node:current
        steps:
        - checkout
        - run:
            name: Install npm dependencies
            command: |
                npm install 

    start_kafka:
        docker:
        - image: cimg/base:stable
        steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: false
        - run:
            name: Install Docker Compose
            command: |
                curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
                chmod +x ~/docker-compose
                mkdir -p ~/.local/bin
                mv ~/docker-compose ~/.local/bin/docker-compose
                export PATH=~/.local/bin:$PATH
        - run:
            name: Start Kafka
            command: |
                export PATH=~/.local/bin:$PATH
                ~/.local/bin/docker-compose up -d
                sleep 30  # Give some time for Kafka to start

    build_and_push_docker_image:
        docker:
        - image: cimg/node:current
        steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: false
        - run:
            name: Build and Push Docker image
            command: |
                docker build -t thiruthanikaiarasu/log-ingestion-server:latest .
                echo $DOCKER_PASSWORD | docker login -u thiruthanikaiarasu --password-stdin
                docker push thiruthanikaiarasu/log-ingestion-server:latest

workflows:
    build_test:
        jobs:
        - install_dependencies
        - start_kafka:
            requires:
                - install_dependencies
        - build_and_push_docker_image:
            requires:
                - start_kafka