version: 2.1
jobs:
    install_dependencies:
        docker:
            - image: circleci/node:current
        steps:
          - checkout
          - run:
                name: Install npm dependencies
                command: |
                    npm install 

    build_and_push_docker_image:
        docker:
            - image: circleci/node:current
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: false
            - run:
                name: Build Docker image
                command: |
                    docker build -t opportune-server -t thiruthanikaiarasu/log-ingestion-server:latest .
                    echo $DOCKER_PASSWORD | docker login -u thiruthanikaiarasu --password-stdin
                    docker push thiruthanikaiarasu/log-ingestion-server:latest

workflows:
    build_test:
        jobs:
            - install_dependencies
            - build_and_push_docker_image
