version: 2.1
jobs:
    install_dependencies:
        docker:
            - image: circleci/node:current
            - image: wurstmeister/kafka:latest
              environment:
                KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092
                KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
                KAFKA_LISTENER_NAME_INSIDE: INSIDE
                KAFKA_LISTENER_PORT: 9092
                KAFKA_LISTENER_INTERFACE: lo0
                KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
                KAFKA_LISTENER_INTERNAL: INSIDE
        steps:
          - checkout
          - run:
                name: Install npm dependencies
                command: |
                    npm install 

    start_kafka:
        docker:
            - image: wurstmeister/kafka:latest
              environment:
                KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092
                KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
                KAFKA_LISTENER_NAME_INSIDE: INSIDE
                KAFKA_LISTENER_PORT: 9092
                KAFKA_LISTENER_INTERFACE: lo0
                KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
                KAFKA_LISTENER_INTERNAL: INSIDE
        steps:
            - run:
                name: Start Kafka
                command: |
                    docker-compose -f docker-compose.yml up -d

    build_and_push_docker_image:
        docker:
            - image: circleci/node:current
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: false
            - run:
                name: Build Docker image
                command: |
                    docker build -t opportune-server -t thiruthanikaiarasu/log-ingestion-server:latest .
                    echo $DOCKER_PASSWORD | docker login -u thiruthanikaiarasu --password-stdin
                    docker push thiruthanikaiarasu/log-ingestion-server:latest

workflows:
    build_test:
        jobs:
            - install_dependencies
            - start_kafka:
                requires:
                    - install_dependencies
            - build_and_push_docker_image:
                requires:
                    - start_kafka
